language: node_js
node_js:
- stable
- '8'
- '10'
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: genus-machina/screech
    node: '10'
